services:
  my-server:
    build: .
    ports:
      - 8081:8080
    depends_on:
      my-redis-server:
        condition: service_healthy
  my-redis-server:
    image: redis
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10