spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team5Project
    username: root
    password: tndiqkr12!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  # Redis 사용할 때 입력
  data:
    redis:
      host: 127.0.0.1
      port: 6379

jwt:
  secret:
    key: asjdkjfxcjvxbjfsdrjhweuhrkalsdjjczxjhkjfhsadsjklas